# -*- coding: utf-8 -*-
"""article_summariser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JNP6YdEXGkNzph1QJZuGXvI_H7i3tmYW
"""

import nltk
from bs4 import BeautifulSoup
from sumy.parsers.html import HtmlParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer as Summarizer
from sumy.nlp.stemmers import Stemmer
from sumy.utils import get_stop_words

def fetch_article(url):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return response.text
        else:
            print(f"Failed to fetch article. Status code: {response.status_code}")
            return None
    except Exception as e:
        print(f"An error occurred while fetching the article: {e}")
        return None

article_url = ("https://www.hindustantimes.com/india-news/air-india-gets-show-cause-notice-over-wheelchair-shortage-after-flyers-death-101708091747166.html")
article_content = fetch_article(article_url)
parsed_content = parse_html(article_content)
summary = summarize_text(parsed_content)
print(summary)